apiVersion: v1
kind: Service
metadata:
  name: kube-ops-view
spec:
  type: NodePort
  selector:
    app: kube-ops-view
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32000
    protocol: TCP
