apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      imagePullSecrets:
      - name: docker-credentials
      containers:
      - name: house-price-predictor-streamlit
        image: lyriqsele/house-price-predictor-streamlit:latest
        ports:
        - containerPort: 8501
        env:
        - name: API_URL
          value: "http://model:8000"