name: MLops CI Workflow
on:
    push:
        branches: [main]
        paths:
            - "src/**"
            - "tests/**"
            - "."

    pull_request:
        branches: [main]
        paths:
            - "src/**"
            - "tests/**"
            - "."

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.11.14

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run Data Preprocessing tests
              run: |
                  python src/data/run_processing.py   --input data/raw/house_data.csv   --output data/processed/cleaned_house_data.csv

            - name: Run Feature Engineering
              run: |
                  python src/features/engineer.py   --input data/processed/cleaned_house_data.csv   --output data/processed/featured_house_data.csv   --preprocessor models/trained/preprocessor.pkl

            - name: Start MLflow server
              run: |
                  docker run -d -p 5555:5555 --name mlflow-server -v ${{ github.workspace }}/mlruns:/mlruns mlflow/mlflow:latest mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlruns --host
            - name: Train Model and Experimentation
              run: |
                  python src/models/train_model.py   --config configs/model_config.yaml   --data data/processed/featured_house_data.csv   --models-dir models   --mlflow-tracking-uri http://localhost:5555

            - name: Clean up MLflow server
              run: |
                  docker stop mlflow-server
                  docker rm mlflow-server
