name: MLops CI Workflow
on:
    push:
        branches: [main]
        paths:
            - "src/**"
            - "tests/**"
            - ".github/workflows/mlops-ci-workflow.yaml"
            - "streamlit_app/**"
    pull_request:
        branches: [main]
        paths:
            - "src/**"
            - "tests/**"
            - ".github/workflows/mlops-ci-workflow.yaml"

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.11.14

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run Data Preprocessing tests
              run: |
                  python src/data/run_processing.py   --input data/raw/house_data.csv   --output data/processed/cleaned_house_data.csv

            - name: Run Feature Engineering
              run: |
                  python src/features/engineer.py   --input data/processed/cleaned_house_data.csv   --output data/processed/featured_house_data.csv   --preprocessor models/trained/preprocessor.pkl

            - name: Train Model and Experimentation
              run: |
                  python src/models/train_model.py   --config configs/model_config.yaml   --data data/processed/featured_house_data.csv   --models-dir models

    push-to-docker:
        needs: build-and-test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and push API image
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: Dockerfile
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/house-price-predictor-api:latest, ${{ secrets.DOCKER_USERNAME }}/house-price-predictor-api:${{ github.sha }}

            - name: Build and push Streamlit image
              uses: docker/build-push-action@v3
              with:
                  context: streamlit_app
                  file: streamlit_app/Dockerfile
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/house-price-predictor-streamlit:latest, ${{ secrets.DOCKER_USERNAME }}/house-price-predictor-streamlit:${{ github.sha }}
